apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy-mysql
  labels:
    env: prod
spec:
  selector:
    matchLabels:
      env: prod      
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-pod
        env: prod
        
    spec:
      containers:
      - name: app-container
        image: sadanchandra99/project1:app-deploy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080